name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the pages branch
  push:
    branches: [ pages ]
  pull_request:
    branches: [ pages ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: cd wild-mongoose-chase
      - uses: actions-rs/cargo@v1
        with:
          command: test
  wasm:
    name: Generate wasm output
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: cd wild-mongoose-chase
      - run: rustup target add wasm32-unknown-unknown
      - run: cargo install -f wasm-bindgen-cli
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --target wasm32-unknown-unknown
      - run: ./wasmhelper.sh
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: wasm_out # The folder the action should deploy.
